'\" t
.\"     Title: dracut.conf
.\"    Author: [see the "AUTHOR" section]
.\" Generator: DocBook XSL Stylesheets v1.77.1 <http://docbook.sf.net/>
.\"      Date: 01/23/2013
.\"    Manual: dracut
.\"    Source: dracut
.\"  Language: English
.\"
.TH "DRACUT\&.CONF" "5" "01/23/2013" "dracut" "dracut"
.\" -----------------------------------------------------------------
.\" * Define some portability stuff
.\" -----------------------------------------------------------------
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.\" http://bugs.debian.org/507673
.\" http://lists.gnu.org/archive/html/groff/2009-02/msg00013.html
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.\" -----------------------------------------------------------------
.\" * set default formatting
.\" -----------------------------------------------------------------
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.\" -----------------------------------------------------------------
.\" * MAIN CONTENT STARTS HERE *
.\" -----------------------------------------------------------------
.SH "NAME"
dracut.conf \- configuration file(s) for dracut
.SH "SYNOPSIS"
.sp
\fI/etc/dracut\&.conf\fR \fI/etc/dracut\&.conf\&.d/*\&.conf\fR
.SH "DESCRIPTION"
.sp
\fIdracut\&.conf\fR is loaded during the initialisation phase of dracut\&. Command line parameter will overwrite any values set here\&. \fIdracut\&.conf\&.d/*\&.conf\fR files are read in alphanumerical order and will overwrite parameters set in \fI/etc/dracut\&.conf\fR\&. Each line specifies an attribute and a value\&. A \fI#\fR indicates the beginning of a comment; following characters, up to the end of the line are not interpreted\&.
.PP
\fBdracutmodules+=\fR"\ \&\fI<dracut modules>\fR\ \&"
.RS 4
Specify a space\-separated list of dracut modules to call when building the initramfs\&. Modules are located in
\fI/usr/lib/dracut/modules\&.d\fR\&.
.RE
.PP
\fBomit_dracutmodules+=\fR"\ \&\fI<dracut modules>\fR\ \&"
.RS 4
Omit a space\-separated list of dracut modules\&.
.RE
.PP
\fBadd_dracutmodules+=\fR"\ \&\fI<dracut modules>\fR\ \&"
.RS 4
Add a space\-separated list of dracut modules\&.
.RE
.PP
\fBdrivers+=\fR"\ \&\fI<kernel modules>\fR\ \&"
.RS 4
Specify a space\-separated list of kernel modules to exclusively include in the initramfs\&. The kernel modules have to be specified without the "\&.ko" suffix\&.
.RE
.PP
\fBadd_drivers+=\fR"\ \&\fI<kernel modules>\fR\ \&"
.RS 4
Specify a space\-separated list of kernel modules to add to the initramfs\&. The kernel modules have to be specified without the "\&.ko" suffix\&.
.RE
.PP
\fBomit_drivers+=\fR"\ \&\fI<kernel modules>\fR\ \&"
.RS 4
Specify a space\-separated list of kernel modules not to add to the initramfs\&. The kernel modules have to be specified without the "\&.ko" suffix\&.
.RE
.PP
\fBinstall_items+=\fR"\ \&\fI<kernel modules>\fR\ \&"
.RS 4
Specify a space\-separated list of files, which are added to the initramfs image\&.
.RE
.PP
\fBfilesystems+=\fR"\ \&\fI<filesystem names>\fR\ \&"
.RS 4
Specify a space\-separated list of kernel filesystem modules to exclusively include in the generic initramfs\&.
.RE
.PP
\fBdrivers_dir=\fR"\fI<kernel modules directory>\fR"
.RS 4
Specify the directory, where to look for kernel modules
.RE
.PP
\fBfw_dir+=\fR"\ \&:\fI<dir>\fR[:\fI<dir>\fR\ \&\&...]\ \&"
.RS 4
Specify additional directories, where to look for firmwares, separated by :
.RE
.PP
\fBinstall_items+=\fR"\ \&\fI<file>\fR[ \fI<file>\fR\ \&\&...]\ \&"
.RS 4
Specify additional files to include in the initramfs, separated by spaces\&.
.RE
.PP
\fBdo_strip=\fR"\fI{yes|no}\fR"
.RS 4
Strip binaries in the initramfs (default=yes)
.RE
.PP
\fBhostonly=\fR"\fI{yes|no}\fR"
.RS 4
Host\-Only mode: Install only what is needed for booting the local host instead of a generic host and generate host\-specific configuration\&.
.RE
.PP
\fBtmpdir=\fR"\fI<temporary directory>\fR"
.RS 4
Specify temporary directory to use\&.
.RE
.if n \{\
.sp
.\}
.RS 4
.it 1 an-trap
.nr an-no-space-flag 1
.nr an-break-flag 1
.br
.ps +1
\fBWarning\fR
.ps -1
.br
.sp
If chrooted to another root other than the real root device, use \-\-fstab and provide a valid \fI/etc/fstab\fR\&.
.sp .5v
.RE
.PP
\fBuse_fstab=\fR"\fI{yes|no}\fR"
.RS 4
Use
\fI/etc/fstab\fR
instead of
\fI/proc/self/mountinfo\fR\&.
.RE
.PP
\fBadd_fstab+=\fR"\ \&\fI<filename>\fR\ \&"
.RS 4
Add entries of
\fI<filename>\fR
to the initramfs /etc/fstab\&.
.RE
.PP
\fBadd_device+=\fR"\ \&\fI<device>\fR\ \&"
.RS 4
Bring up
\fI<device>\fR
in initramfs,
\fI<device>\fR
should be the device name\&. This can be useful in hostonly mode for resume support when your swap is on LVM an encrypted partition\&.
.RE
.PP
\fBmdadmconf=\fR"\fI{yes|no}\fR"
.RS 4
Include local
\fI/etc/mdadm\&.conf\fR
(default=yes)
.RE
.PP
\fBlvmconf=\fR"\fI{yes|no}\fR"
.RS 4
Include local
\fI/etc/lvm/lvm\&.conf\fR
(default=yes)
.RE
.PP
\fBfscks=\fR"\ \&\fI<fsck tools>\fR\ \&"
.RS 4
Add a space\-separated list of fsck tools\&. If nothing is specified, the default is: "umount mount /sbin/fsck* xfs_db xfs_check xfs_repair e2fsck jfs_fsck reiserfsck btrfsck"\&. The installation is opportunistic (non\-existing tools are ignored)\&.
.RE
.PP
\fBnofscks=\fR"\fI{yes|no}\fR"
.RS 4
If specified, inhibit installation of any fsck tools\&.
.RE
.sp
\fBro_mnt\fR Mount \fI/\fR and \fI/usr\fR read\-only by default\&.
.PP
\fBkernel_cmdline=\fR"\fIparameters\fR"
.RS 4
Specify default kernel command line parameters
.RE
.PP
\fBkernel_only=\fR"\fI{yes|no}\fR"
.RS 4
Only install kernel drivers and firmware files\&. (default=no)
.RE
.PP
\fBno_kernel=\fR"{yes|no}"
.RS 4
Do not install kernel drivers and firmware files (default=no)
.RE
.PP
\fBstdloglvl\fR="\fI{0\-6}\fR"
.RS 4
Set logging to standard error level\&.
.RE
.PP
\fBsysloglvl\fR="\fI{0\-6}\fR"
.RS 4
Set logging to syslog level\&.
.RE
.PP
\fBfileloglvl=\fR"\fI{0\-6}\fR"
.RS 4
Set logging to file level\&.
.RE
.PP
\fBlogfile=\fR"\fI<file>\fR"
.RS 4
Path to log file\&.
.RE
.PP
\fBshow_modules=\fR"\fI{yes|no}\fR"
.RS 4
Print included module\(cqs name to standard output during build\&.
.RE
.SH "FILES"
.PP
\fI/etc/dracut\&.conf\fR
.RS 4
Old configuration file\&. You better use your own file in
\fI/etc/dracut/conf\&.d/\fR\&.
.RE
.PP
\fI/etc/dracut\&.conf\&.d/\fR
.RS 4
Any
\fI/etc/dracut\&.conf\&.d/*\&.conf\fR
file can overwrite the values in
\fI/etc/dracut\&.conf\fR\&. The configuration files are read in alphanumerical order\&.
.RE
.SH "AUTHOR"
.sp
Harald Hoyer
.SH "SEE ALSO"
.sp
\fBdracut\fR(8) \fBdracut\&.cmdline\fR(7)
