#!/bin/sh

version="$1"
bootopt=""

# passing the kernel version is required
[ -z "${version}" ] && exit 0

# kernel-package passes an extra arg
if [ -n "$2" ]; then
	if [ -n "${KERNEL_PACKAGE_VERSION}" ]; then
		# exit if custom kernel does not need an initramfs
		[ "$INITRD" = 'No' ] && exit 0
		bootdir=$(dirname "$2")
	fi
fi

# avoid running multiple times
if [ -n "$DEB_MAINT_PARAMS" ]; then
	eval set -- "$DEB_MAINT_PARAMS"
	if [ -z "$1" ] || [ "$1" != "configure" ]; then
		exit 0
	fi
fi

if [ -z "$bootdir" ]; then
    bootdir=/boot
fi

# we're good - create initramfs
echo "dracut: Generating $bootdir/initramfs-${version}.img"
dracut -q --force $bootdir/initramfs-${version}.img "${version}" >&2
