Index: dracut/Makefile
===================================================================
--- dracut.orig/Makefile	2013-02-01 15:23:16.072974664 +0100
+++ dracut/Makefile	2013-02-06 16:41:34.089974388 +0100
@@ -35,7 +35,7 @@
 
 .PHONY: install clean archive rpm testimage test all check AUTHORS doc
 
-all: syncheck dracut-version.sh dracut-install
+all: syncheck dracut-version.sh
 
 DRACUT_INSTALL_OBJECTS = \
         install/dracut-install.o \
