Index: dracut/Makefile
===================================================================
--- dracut.orig/Makefile	2013-08-08 11:12:36.046706016 +0200
+++ dracut/Makefile	2013-08-08 22:37:32.407949928 +0200
@@ -40,7 +40,7 @@
 
 .PHONY: install clean archive rpm testimage test all check AUTHORS doc dracut-version.sh
 
-all: dracut-version.sh dracut-install
+all: dracut-version.sh
 
 DRACUT_INSTALL_OBJECTS = \
         install/dracut-install.o \
