#!/bin/sh

set -e


mk_initrd() {

    if ls /boot/vmlinu[zx]-* >/dev/null 2>&1; then

    # Regenerate initramfs for all kernel that are installed
    for kversion in `ls /boot/vmlinu[zx]-* | sed -e 's#/boot/vmlinu.-##'`; do
        /etc/kernel/postinst.d/dracut $kversion
    done
    fi
}


if [ "$1" = triggered ]; then
    # check if any kernel is available
    # do not call dracut if no kernel was found
    mk_initrd
fi


#DEBHELPER#
